name: 'Delete workflow runs'
description: 'An action to delete workflow runs in a repository.'
author: 'Bright Ran'

inputs:
  token:
    description: 'The token used to authenticate.'
    required: true
    default: ${{ github.token }}

  repository:
    description: 'The name of the repository.'
    required: true
    default: ${{ github.repository }}

  keep_minimum_runs:
    description: 'The Each workflow runs minimally to retain.'
    required: true
    default: 3

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'delete'
  color: 'red'